config/routes.rb
Rails.application.routes.draw do
  # ... edited by app gen (other pages)
  get 'other_pages/map', as: 'map'
  get 'other_pages/email_form', as: 'email_form'
  post 'other_pages/email_send'
  get 'other_pages/under_construction', as: 'under_construction'

  # edited by app gen (landing page)
  get 'landing_page/index'
  root 'landing_page#index'

  resources :products, only: [:index, :show] do
    post 'buy', on: :collection
    post 'setup_purchase', on: :collection
  end

  # ... disabled by landing page edit
  # root 'products#index'

  # ... edited by app gen (user resource generation)
  get 'users/show'
  get 'users/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  # ... edited by app gen (product resource)
  default_scope { order :name }

  belongs_to :user
end

app/controllers/products_controller.rb
# ... edited by app gen (product resource)

class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :buy, :setup_purchase]

  def setup_purchase
    @publishable_key = Rails.configuration.stripe.fetch :publishable_key

    # For use with redirecting "back" inside buy action
    session[:setup_purchase_referrer] = request.referer
  end

  # POST /products/1
  def buy
    token = params[:token].freeze
    customer = Stripe::Customer.create(
      email: token[:email], source: token[:id]
    )

    Stripe::Charge.create(
      customer:    customer.id,
      amount:      (@product.price.to_f * 100).to_i,
      description: "#{@product.id}:#{@product.name}",
      currency:    'usd'
    )

    # ... robustify: wait until we receive confirmation from Stripe
    #   that the purchase succeeded before decrementing stock.
    #   Also, add a purchase quantity in the view and reflect that here
    #   instead of hard-coding the number (1 in this case).
    @product.update(in_stock: @product.in_stock - 1)

    @product.update(user: current_user) if current_user

    flash[:successful_purchase] = @product.attributes

    # currency = view_context.number_to_currency @product.price
    # flash[:success] = 'Thank you for purchasing' \
    #   " '#{@product.name}' for '#{currency}'."
  rescue Stripe::CardError => exc
    msg = "#{exc.class}: #{exc.message}"
    Rails.logger.error(msg)
    flash[:error] = msg
  ensure
    # We can't because one more level of redirection (the setup)
    # The "back" is actually purchasing the thing. For example...
    #   redirect_back fallback_location: products_url
    # That's why we have to use session
    redirect_to(session[:setup_purchase_referrer] || products_url)
  end

  # GET /products
  def index
    # ... flash and order edit
    #     flash.keep because because redirected 2x (setup_purchase => buy)???
    flash.keep if request.referer =~ /setup_purchase/

    @current_page_number = (params[:page] || 1).to_i
    @all_products = Product.order(:name)
    @products = @all_products.page(@current_page_number).per(8)

    @special_offers = [@all_products.first, @all_products.last]

    # ... can't cache. If we do, flash won't work.
    #     (Try buying something, the redirect back to the
    #       page won't show purchase confirmation.)
    # return if !Rails.env.production?
    # expires_in 1.year, public: true, must_revalidate: true
  end

  # GET /products/1
  def show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def product_params
    params.require(:product).permit(
      :name, :description, :price, :in_stock, :sku, :media
    )
  end
end

app/views/products/_content.html.erb
<!-- ... edited by app gen (product resource) -->

    <div id="content" class="col-sm-9">
      <% @products.each_slice(2) do |slice| %>
        <div class="row">
          <% slice.each do |product| %>
            <div class="col-sm-6 card_custom">
              <div class="panel">
                <div class="panel-heading">
                  <%= link_to product_path(product) do %>
                    <%= image_tag product.media %>
                  <% end -%>
                </div>

                <div class="panel-body">
                  <div class="row pull-right">
                    <a href="#facebook"><span class="fa fa-facebook fa-2x"></span></a>
                    <a href="#twitter"><span class="fa fa-twitter fa-2x"></span></a>
                    <a href="#share"><span class="glyphicon glyphicon-share-alt fa-2x"></span></a>
                  </div>

                  <%= content_tag :h3, product.name, class: 'name' %>
                  <%= content_tag :div, product.description, class: 'description' %>
                  <%= content_tag :div, Faker::Hipster.paragraph, class: 'long' %>

                  <div class="col-xs-6 last_row">
                    <%= content_tag :h3, '$ ' + product.price.to_s, class: 'price' %>
                  </div>

                  <div class="col-xs-6 last_row">
                    <div class="row buttons pull-right">
                      <%= button_to(
                            'Buy',
                            { action: :setup_purchase, controller: :products, id: product.id },
                            form_class: 'form-inline',
                            class: 'btn btn-primary'
                          ) %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end -%>
        </div>
      <% end -%>

      <%= paginate @products %>
    </div>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :in_stock %>
    <%= f.number_field :in_stock %>
  </div>

  <div class="field">
    <%= f.label :sku %>
    <%= f.number_field :sku %>
  </div>

  <div class="field">
    <%= f.label :media %>
    <%= f.text_field :media %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_left_column.html.erb
<!-- ... edited by app gen (product resource) -->

    <div id="left_column" class="col-sm-3">
      <div class="panel panel-primary">
        <div class="panel-heading">Categories</div>

        <div class="list-group">
          <a href="#" class="list-group-item">Groceries</a>
          <a href="#" class="list-group-item">Engines</a>
          <a href="#" class="list-group-item">Power Supplies</a>
          <a href="#" class="list-group-item">Tools</a>
          <a href="#" class="list-group-item">Paper Products</a>
        </div>
      </div>

      <div class="panel panel-primary">
        <div class="panel-heading">Filter By</div>

        <div class="list-group">
          <a href="#" class="list-group-item">Manufacturer</a>
          <a href="#" class="list-group-item">Engine</a>
          <a href="#" class="list-group-item">Power Supply</a>
          <a href="#" class="list-group-item">Capacity</a>
          <a href="#" class="list-group-item">Sweetness</a>
        </div>
      </div>

      <hr>

      <a href="#">
        <img class="img-responsive" src="https://placehold.it/400x170/654321?text=SALE!">
      </a>

      <hr>

      <div id="special_offers" class="panel panel-default">
        <div class="panel-heading">Special Offers</div>

        <div class="panel-body">
          <% @special_offers.each do |special_offer| %>
            <div class="media">
              <div class="media-left">
                <%= link_to product_path(special_offer) do %>
                  <%= image_tag special_offer.media, class: 'panel-image-preview' %>
                <% end -%>
              </div>
              <div class="media-body">
                <h4 class="media-heading"><%= special_offer.name %></h4>
                Brief description
                <br>
                <strong>$ <%= special_offer.price %></strong>
              </div>
            </div>
          <% end -%>
        </div>
      </div>
    </div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<!-- ... edited by app gen (product resource) -->

<% provide :title, "Products Page #{@current_page_number}"%>

<div id="products">
  <div class="row">
    <%= render partial: 'left_column' %>
    <%= render partial: 'content' %>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/setup_purchase.html.erb
<!-- ... edited by app gen (product resource) -->

<% provide :title, "Buying **#{@product.name}**..." %>

<script src="https://checkout.stripe.com/checkout.js"></script>

<button id="customButton" style="visibility: hidden;">Purchase</button>

<%= render template: 'products/show' %>

<script>
var transactionNotSubmitted = true;

/* global StripeCheckout */

var handler = StripeCheckout.configure({
  key: '<%= @publishable_key %>',
  image: 'https://stripe.com/img/documentation/checkout/marketplace.png',
  locale: 'auto',
  token: function tokenCB(token) {
    transactionNotSubmitted = false;

    // You can access the token ID with `token.id`.
    // Get the token ID to your server-side code for use.
    $.ajax({
      url: '<%= buy_products_path %>',
      // dataType: 'json',
      type: 'post',
      contentType: 'application/json',
      data: JSON.stringify({
        // ...
        id: '<%= @product.id %>',
        token: token,
        email: token.email
      }),
      processData: false,
      success: function successCB(data) {
        console.log('SUCCESS...');
        console.log(data);
      },
      error: function errorCB(jqXhr, textStatus, errorThrown ) {
        console.log(jqXhr.responseText);
        console.log(textStatus);
        console.log(errorThrown);
      }
    });
  }
});

document.getElementById('customButton').addEventListener('click', function eventListenerCB(ev) {
  // Open Checkout with further options:
  handler.open({
    name: 'Stripe.com',
    description: '<%= @product.name %>',
    // zipCode: true,
    amount: parseInt('<%= @product.price * 100 %>', 10),

    closed: function stripeClosed() {
      // https://stackoverflow.com/questions/15555567/rails-how-to-use-jquery-to-redirect-to-root-page-in-different-environments
      console.log('Stripe closed, the referrer... ' + '<%= request.referer %>');
      console.log({ transactionNotSubmitted: transactionNotSubmitted });

      if (transactionNotSubmitted) {
        window.location = '<%= request.referer %>';
      }
    }
  });

  ev.preventDefault();
});

// Close Checkout on page navigation: /
window.addEventListener('popstate', function popStateCB() {
  handler.close();
});

$(document).ready(function buttonClickCB() {
  document.getElementById('customButton').click();
});

</script>

app/views/products/show.html.erb
<!-- ... edited by app gen (product resource) -->

<% provide :title, @product.name %>

<%= stylesheet_link_tag 'index/show', media: 'all', 'data-turbolinks-track': 'reload'  %>

<div id="show">
  <div class="media">
    <div class="media-left">
      <%= link_to '#' do %>
        <%= image_tag @product.media, class: 'media-object' %>
      <% end -%>
    </div>
    <div class="media-body">
      <%= content_tag :h4, @product.name, class: 'media-heading' %>

      <hr>

      <p>
        <strong>Description:</strong>
        <%= @product.description %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= @product.price %>
      </p>

      <p>
        <strong>In stock:</strong>
        <%= @product.in_stock %>
      </p>

      <p>
        <strong>Sku:</strong>
        <%= @product.sku %>
      </p>
    </div>
  </div>
</div>